routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// TODO home page slider image by url! 


Auth::routes();



Route::group(['namespace' => 'Admin', 'prefix' => 'master', 'middleware' => ['auth', 'isMaster']], function () {
    Route::get('/', 'AdminHomeController@index')->name('master');
    Route::get('/products_management', 'AdminHomeController@productManagment')->name('product_managment');

    Route::resource('users', 'AdminUserController');
    Route::resource('settings', 'AdminSettingController', ['only' => ['edit', 'update']]);
    Route::resource('slider', 'AdminSliderController', ['except' => ['show']]);
    Route::resource('banner', 'AdminBannerController', ['except' => ['show', 'create', 'store']]);

    Route::post('rebuildtree', 'AdminBaseController@rebuildTree')->name('rebuildTree');


    Route::resource('page', 'AdminPageController', ['except' => ['show']]);
    Route::resource('portfolio', 'AdminPortfolioController');
    Route::resource('news', 'AdminNewsController', ['except' => ['show']]);
    Route::resource('currency', 'AdminCurrencyController', ['except' => ['show', 'destroy', 'create', 'edit']]);

    Route::group(['prefix' => 'products_management'], function () {
        Route::resource('categories', 'AdminCategoriesController', ['except' => ['show']]);
        Route::resource('brands', 'AdminBrandsController', ['except' => ['show']]);
        Route::resource('products', 'AdminProductsController');
        Route::get('products/loadAjax', 'AdminProductsController@loadAjax');
        Route::resource('labels', 'AdminLabelController', ['except' => ['show']]);
        Route::resource('options', 'AdminOptionsController', ['except' => ['show']]);
        Route::resource('colors', 'AdminColorController', ['except' => ['show', 'create']]);
        Route::resource('features', 'AdminFeatureController', ['except' => ['show']]);
        Route::resource('delivery', 'AdminDeliveryController', ['except' => ['show', 'create']]);
        Route::resource('payment', 'AdminPaymentController', ['except' => ['show', 'create']]);
        Route::resource('groups', 'AdminProductGroupsController');

    });

    // Orders
    Route::resource('order', 'AdminOrderController');
    Route::resource('comments', 'AdminCommentsController', ['except' => ['show', 'create', 'edit', 'store']]);
    Route::resource('questions', 'AdminProductQuestion');
    Route::resource('feedback', 'AdminFeedbackController');
    Route::resource('import', 'AdminImportController');

});


Route::group(['prefix' => LaravelLocalization::setLocale()], function () {
    /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
    Route::get('/', 'Site\HomeController@index');
    Route::get('/loadAjax/{data}', 'Site\HomeController@ajax');
    Route::get('/loadCart/{data}', 'Site\HomeController@loadCart');
    Route::post('/makeComment', 'Site\HomeController@makeComment');
    Route::post('question', 'Site\HomeController@makeQuestion');
    Route::post('feedback', 'Site\HomeController@makeFeedback');
    Route::get('/search', 'Site\HomeController@search');
    Route::get('catalog', 'Site\CatalogController@index');
    Route::get('catalog/{name}', 'Site\CatalogController@parse');
    Route::get('/personal', 'Site\PersonalController@index');
    Route::get('/personal/history', 'Site\PersonalController@history');
    Route::post('/personal/update', 'Site\PersonalController@update');
    Route::get('/cart', 'Site\OrderController@showCart');
    Route::get('/brand/{brand}', 'Site\PageController@showBrand');
	//Glide
    Route::get('img/{path}', function ($path, League\Glide\Server $server, Illuminate\Http\Request $request) {
        if ($request->w > 2000 || $request->h > 1000)
            return null;
        $server->outputImage('/images/' . $path, $request->all());
    })->where('path', '.+');
    Route::get('news/{new?}', 'Site\NewsController@index');
    Route::post('/addToCart', 'Site\OrderController@addToCart');
    Route::get('/makeconment', 'Site\HomeController@makeconment');
    Route::post('/dropFromCart', 'Site\OrderController@dropFromCart');
    Route::post('makeOrder', 'Site\OrderController@makeOrder');
    Route::get('/logout', function () {
        Auth::logout();
        return redirect('/');
    });
    Route::get('{page}', 'Site\PageController@index');
});

app/Models/Portfolio.php
<?php

namespace App\Models;

use App\Http\Controllers\Admin\AdminPortfolioController;
use Illuminate\Database\Eloquent\Model;
use Image;


class Portfolio extends Model
{
    protected $fillable = ['name', 'body', 'slug', 'meta_title', 'meta_keywords', 'meta_description'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function images()
    {
        return $this->morphMany(Picture::class, 'picturetable');
    }

    public static function boot()
    {
        parent::boot();

        self::deleting(function ($model) {
            $imageIDs = $model->images()->pluck('id');
            Picture::deleteImages($imageIDs, AdminPortfolioController::getParams());
        });
    }

}

resources/views/admin/portfolio/create.blade.php
@extends('admin.layout')

@section('main')

    <h1>{{ $title }}
        <a href="{{ route('portfolio.index') }}" class="btn btn-primary" title="Назад"
           data-toggle="tooltip"><span
                    class="fa fa-arrow-circle-left"></span></a>

        <button id="send-form" class="btn btn-success" title="Сохранить" data-toggle="tooltip"><i class="fa fa-floppy-o"
                                                                                               aria-hidden="true"></i>
        </button>


        @if(Session::has('success'))
            <span class="btn alert-success" role="alert">{{ Session::get('success') }}</span>
        @elseif(Session::has('error'))
            <span class="btn alert-danger" role="alert">{{ Session::get('error') }}</span>
        @endif

        @if (count($errors) > 0)
            @foreach ($errors->all() as $error)
                <div class="btn alert-danger">
                    {{ $error }}
                </div>
            @endforeach
        @endif
    </h1><br>

    {!! Form::open(['route'=> ['portfolio.store'], 'class' => 'form-horizontal', 'role' => 'form'] ) !!}
    @include('admin.portfolio.form')
    {!! Form::close() !!}


    <script>
        $('#send-form').click(function () {
            $('form').submit();
        });

        meta_title_touched = false;
        url_touched = false;

        $('input[name="slug"]').change(function () {
            url_touched = true;
        });

        $('input[name="name"]').keyup(function () {
            if (!url_touched)
                $('input[name="slug"]').val(generate_url());

            if (!meta_title_touched)
                $('input[name="meta_title"]').val($('input[name="name"]').val());
        });

        $('input[name="meta_title"]').change(function () {
            meta_title_touched = true;
        });

        function generate_url() {
            url = $('input[name="name"]').val();
            url = url.replace(/[\s]+/gi, '-');
            url = translit(url);
            url = url.replace(/[^0-9a-z_\-]+/gi, '').toLowerCase();
            return url;
        }

        function translit(str) {
            var ru = ("А-а-Б-б-В-в-Ґ-ґ-Г-г-Д-д-Е-е-Ё-ё-Є-є-Ж-ж-З-з-И-и-І-і-Ї-ї-Й-й-К-к-Л-л-М-м-Н-н-О-о-П-п-Р-р-С-с-Т-т-У-у-Ф-ф-Х-х-Ц-ц-Ч-ч-Ш-ш-Щ-щ-Ъ-ъ-Ы-ы-Ь-ь-Э-э-Ю-ю-Я-я").split("-")
            var en = ("A-a-B-b-V-v-G-g-G-g-D-d-E-e-E-e-E-e-ZH-zh-Z-z-I-i-I-i-I-i-J-j-K-k-L-l-M-m-N-n-O-o-P-p-R-r-S-s-T-t-U-u-F-f-H-h-TS-ts-CH-ch-SH-sh-SCH-sch-'-'-Y-y-'-'-E-e-YU-yu-YA-ya").split("-")
            var res = '';
            for (var i = 0, l = str.length; i < l; i++) {
                var s = str.charAt(i), n = ru.indexOf(s);
                if (n >= 0) {
                    res += en[n];
                }
                else {
                    res += s;
                }
            }
            return res;
        }
    </script>
@stop

resources/views/admin/portfolio/edit.blade.php
@extends('admin.layout')

@section('main')

    <h1>{{ $title }}
        <a href="{{ route('portfolio.index') }}" class="btn btn-primary" title="Назад"
           data-toggle="tooltip"><span
                    class="fa fa-arrow-circle-left"></span></a>

        <button id="send-form" class="btn btn-success" title="Сохранить" data-toggle="tooltip"><i class="fa fa-floppy-o"
                                                                                                  aria-hidden="true"></i>
        </button>


        @if(Session::has('success'))
            <span class="btn alert-success" role="alert">{{ Session::get('success') }}</span>
        @elseif(Session::has('error'))
            <span class="btn alert-danger" role="alert">{{ Session::get('error') }}</span>
        @endif

        @if (count($errors) > 0)
            @foreach ($errors->all() as $error)
                <div class="btn alert-danger">
                    {{ $error }}
                </div>
            @endforeach
        @endif
    </h1><br>

    {{ Form::model($item, ['route'=> ['portfolio.update', $item->id], 'class' => 'form-horizontal', 'role' => 'form'] ) }}
    {{ method_field('PATCH') }}
    @include('admin.portfolio.form')
    {{ Form::close() }}


    <script>
        $('#send-form').click(function () {
            $('form').submit();
        });

        meta_title_touched = false;
        url_touched = false;

        $('input[name="slug"]').change(function () {
            url_touched = true;
        });

        $('input[name="name"]').keyup(function () {
            if (!url_touched)
                $('input[name="slug"]').val(generate_url());

            if (!meta_title_touched)
                $('input[name="meta_title"]').val($('input[name="name"]').val());
        });

        $('input[name="meta_title"]').change(function () {
            meta_title_touched = true;
        });

        function generate_url() {
            url = $('input[name="name"]').val();
            url = url.replace(/[\s]+/gi, '-');
            url = translit(url);
            url = url.replace(/[^0-9a-z_\-]+/gi, '').toLowerCase();
            return url;
        }

        function translit(str) {
            var ru = ("А-а-Б-б-В-в-Ґ-ґ-Г-г-Д-д-Е-е-Ё-ё-Є-є-Ж-ж-З-з-И-и-І-і-Ї-ї-Й-й-К-к-Л-л-М-м-Н-н-О-о-П-п-Р-р-С-с-Т-т-У-у-Ф-ф-Х-х-Ц-ц-Ч-ч-Ш-ш-Щ-щ-Ъ-ъ-Ы-ы-Ь-ь-Э-э-Ю-ю-Я-я").split("-")
            var en = ("A-a-B-b-V-v-G-g-G-g-D-d-E-e-E-e-E-e-ZH-zh-Z-z-I-i-I-i-I-i-J-j-K-k-L-l-M-m-N-n-O-o-P-p-R-r-S-s-T-t-U-u-F-f-H-h-TS-ts-CH-ch-SH-sh-SCH-sch-'-'-Y-y-'-'-E-e-YU-yu-YA-ya").split("-")
            var res = '';
            for (var i = 0, l = str.length; i < l; i++) {
                var s = str.charAt(i), n = ru.indexOf(s);
                if (n >= 0) {
                    res += en[n];
                }
                else {
                    res += s;
                }
            }
            return res;
        }
    </script>
@stop

resources/views/admin/portfolio/form.blade.php
<ul class="nav nav-tabs" id="myTab">
    <li class="active"><a href="#tab_a" data-toggle="tab">Запись</a></li>
    <li><a href="#tab_b" data-toggle="tab">Параметры страницы</a></li>
</ul>
<div class="tab-content">

    <div class="tab-pane active" id="tab_a">
        <div class="form-group">&nbsp;</div>
        <div class="tab-content">
            <div class="form-group">
                {{ Form::label('name', 'Название', ['class'=>'col-sm-2 control-label'] ) }}
                <div class="col-sm-10">
                    {{ Form::text('name', old('name') ? old('name') : $item->name, ['class'=>'form-control', 'autocomplete' => 'off'] ) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('body', 'Текст страницы', ['class'=>'col-sm-2 control-label'] ) }}
                <div class="col-sm-10">
                    {{ Form::textarea('body', old('body') ? old('body') : $item->body, ['class'=>'form-control editor'] ) }}
                </div>
            </div>
        </div>
    </div>


    <div class="tab-pane" id="tab_b">
        <div class="form-group">&nbsp;</div>

        @if( !in_array( $item->slug, ['404']) )
            <div class="form-group">
                {{ Form::label('slug', 'Адрес', ['class'=>'col-sm-2 control-label'] ) }}
                <div class="col-sm-10">
                    <div class="input-group">
                        <span class="input-group-addon">&nbsp;/&nbsp;</span>
                        {{ Form::text('slug', old('slug') ? old('slug') : $item->slug, ['class'=>'form-control', 'id' => 'inputSlug', 'autocomplete' => 'off'] ) }}
                    </div>
                </div>
            </div>
        @endif

        <div class="form-group">
            {{ Form::label('meta_title', 'Заголовок', ['class'=>'col-sm-2 control-label'] ) }}
            <div class="col-sm-10">
                {{ Form::text('meta_title', old('meta_title') ? old('meta_title') : $item->meta_title, ['class'=>'form-control', 'id' => 'inputMetaTitle', 'autocomplete' => 'off'] ) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('meta_keywords', 'Ключевые слова', ['class'=>'col-sm-2 control-label'] ) }}
            <div class="col-sm-10">
                {{ Form::text('meta_keywords', old('meta_keywords') ? old('meta_keywords') : $item->meta_keywords, ['class'=>'form-control', 'id' => 'inputMetaTitle', 'autocomplete' => 'off'] ) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('meta_description', 'Описание', ['class'=>'col-sm-2 control-label'] ) }}
            <div class="col-sm-10">
                {{ Form::text('meta_description', old('meta_description') ? : $item->meta_description, ['class'=>'form-control', 'autocomplete' => 'off'] ) }}
            </div>
        </div>

    </div>
</div>

resources/views/admin/portfolio/index.blade.php
@extends('admin.layout')
@section('main')
    <h1>
        <span class="glyphicon glyphicon-camera"></span>
        {{ $title }}
        <a href="{{ route('master') }}" class="btn btn-primary" title="Назад" data-toggle="tooltip"><span
                    class="fa fa-arrow-circle-left"></span></a>
        <a href="{{ route('portfolio.create') }}" id="send-form" class="btn btn-success"
           title="Cоздать альбом"
           data-toggle="tooltip"><span
                    class="fa fa-plus"></span></a>

        @if($count > 0)
            <span class="label label-primary" style="font-size: 14px;">
			{{ $count }}
                {{ Lang::choice('альбом|альбома|альбомов', $count, [], 'ru') }}
        </span>
        @else
            <div class="btn alert-warning" role="alert">
                У вас еще нет альбомов
            </div>
        @endif

        @if(Session::has('success'))
            <span class="btn alert-success" role="alert">{{ Session::get('success') }}</span>
        @elseif(Session::has('error'))
            <span class="btn alert-danger" role="alert">{{ Session::get('error') }}</span>
        @endif

        @if (count($errors) > 0)
            @foreach ($errors->all() as $error)
                <div class="btn alert-danger">
                    {{ $error }}
                </div>
            @endforeach
        @endif
    </h1><br>

    @if ($count)
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                        <span class="btn btn-warning" title="Выбрать все" data-toggle="tooltip"
                              id="check-all"><i class="glyphicon glyphicon-ok"
                                                aria-hidden="true"></i></span>
                    <button class="delete-selected btn btn-danger"
                            title="Удалить выбранные" data-toggle="tooltip">
                        <span class="glyphicon glyphicon-trash"></span></button>
                </div>
            </div>
        </div>

        {!! Form::open(['route' => ['portfolio.destroy', 'desctroy']]) !!}
        {{ method_field('DELETE') }}
        <table class="table">
            <tr>
                <th style="width: 40%;">Название</th>
                <th style="text-align: right;">Управление</th>
            </tr>
            @foreach ($items as $item)
                <tr>
                    <td style="vertical-align: middle">
                        {{ Form::checkbox('check[]', $item->id, false, ['id' => 'check'.$item->id, 'class' => 'custom-check']) }}
                        {{ Form::label('check'.$item->id, '1', ['class' => 'custom-label-for-check']) }}
                        {{--<input name="check[]" value="{{ $item->id }}"type="checkbox">--}}
                        <a class="black_link" title="Перейти к альбому" data-toggle="tooltip"
                           href="{{ route('portfolio.show', $item->id) }}">
                            {{ $item->name }}</a>
                    </td>
                    <td style="text-align: right;">
                        <div class="btn-group">
                            <a title="Редактировать" href="{{ route('portfolio.edit', ['id' => $item->id]) }}"
                               data-toggle="tooltip"
                               class="btn btn-success"><span class="glyphicon glyphicon-pencil"></span></a>
                            <span class="delete-this-id btn btn-danger" title="Удалить"
                                  data-toggle="tooltip"><span
                                        class="glyphicon glyphicon-remove"></span>
                            </span>
                        </div>
                    </td>
                </tr>
            @endforeach
        </table>
        {{ Form::close() }}

    @endif
    {{ $items->links() }}

    <script>
        $(function () {
            var flag = false;
            $(".delete-selected, .unconfirm-delete, .delete-this-id").click(function () {
                flag = !flag;
                if (flag)
                    move = "50%";
                else move = "-50%";

                $('.confirm-message').stop().animate({
                    top: move
                }, 300);
            });
            $(".confirm-delete").click(function () {
                $('form').submit();
            });
            $(".unconfirm-delete").click(function () {
                $('input[type=checkbox]:checked').prop('checked', false);
            });
            $(".delete-this-id").click(function () {
                $(this).closest('tr').find('input:checkbox').prop('checked', true);
            });
            $("#check-all").on('click', function () {
                $('input[type="checkbox"][name*="check"]').prop('checked', $('input[type="checkbox"][name*="check"]:not(:checked)').length > 0);
            });
        })
    </script>
@endsection

resources/views/admin/portfolio/show.blade.php
@extends('admin.layout')
@section('main')
    <h1>
        <span class="glyphicon glyphicon-camera"></span>
        Портфолио: {{ $title }}
        @if($count > 0)
            <span class="btn btn-primary" style="font-size: 14px; font-weight: bold;">
			{{ $count }}
                {{ Lang::choice('изображение|изображения|изображений', $count, [], 'ru') }}
        </span>
        @else
            <div class="btn alert-warning" role="alert">
                Изображения отсутствуют
            </div>
        @endif
        <a href="{{ route('portfolio.index') }}" class="btn btn-primary" title="Назад" data-toggle="tooltip"><span
                    class="fa fa-arrow-circle-left"></span></a>
        <button id="upload-form" class="btn btn-success" title="Загрузить изображения" data-toggle="tooltip"><i
                    class="fa fa-upload"></i>
        </button>

        <span class="btn btn-warning" title="Выбрать все" data-toggle="tooltip"
              id="check-all"><i class="glyphicon glyphicon-ok"
                                aria-hidden="true"></i></span>
        <button class="delete-selected btn btn-danger"
                title="Удалить выбранные" data-toggle="tooltip">
            <span class="glyphicon glyphicon-trash"></span></button>


        @if(Session::has('success'))
            <span class="btn alert-success" role="alert">{{ Session::get('success') }}</span>
        @elseif(Session::has('error'))
            <span class="btn alert-danger" role="alert">{{ Session::get('error') }}</span>
        @endif

        @if (count($errors) > 0)
            @foreach ($errors->all() as $error)
                <div class="btn alert-danger">
                    {{ $error }}
                </div>
            @endforeach
        @endif
    </h1><br>

    <div class="confirm-message alert alert-info text-center"
         style="position: fixed; top: -50%; left: 0; right: 0; z-index: 10">
        Подтвердите удаление записей из БД &nbsp;
        <span class="confirm-delete btn btn-success">Да</span>
        <span class="unconfirm-delete btn btn-danger">Нет</span>
    </div>

    {!! Form::model( $model, ['route' =>['portfolio.store', 'id'=> $model->id],'id' => 'upload-images','class' => 'form-horizontal', 'role' => 'form', 'files' => true]) !!}
    {{ Form::hidden('picture', true) }}
    <div class="col-sm-12">
        <div class="form-group">
            {!! Form::label('image', 'Изображение', array('class'=>'col-sm-2 control-label') ) !!}
            <div class="col-sm-8">
                {!! Form::file('image[]',array('class' => 'filestyle', 'data-value'=> '',
                'data-buttonText' => 'Выберите файлы', 'data-buttonName' => 'btn-primary',
                'data-icon' => 'true' , 'multiple' => 'true', 'required') ) !!}
                <span>Рекомендуемый размер изображения XxXpx.</span>
            </div>
        </div>
    </div>
    {{ Form::close() }}

    @if($count)
        {!! Form::open(['route' => ['portfolio.destroy', 'destroy', 'id' => 'delete-form']]) !!}
        {{ method_field('DELETE') }}
        <div class="row">
            @foreach ($items as $item )
                <div class="col-sm-6 col-md-2">
                    <div class="thumbnail">
                        <img style="width: 100%;" alt="{{ $item->name }}"
                             src="{{ File::exists(public_path('uploads/'.$item->name)) ? asset('uploads/'.$item->name) : asset('images/noimg.jpg')}}">
                        <div class="caption">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default" title="Выбрать слайд"><input
                                            style="margin: 0;" name="check[]"
                                            value="{{ $item->id }}"
                                            type="checkbox"></button>

                                <button title="Удалить" data-toggle="tooltip" type="submit"
                                        class="delete-this-id btn btn-danger"><span
                                            class="glyphicon glyphicon-remove"></span></button>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>

        <div class="select_form">
            <label id="check_all" class="btn btn-primary">Выбрать все</label>
            <button type="submit" style="" class="btn btn-danger">Удалить выбранные</button>
        </div>
        {!! Form::close() !!}

    @endif
    <script>
        $(function () {
            $(":checkbox").click(function (event) {
                return $(this).parent().click();
            });

            $('button').click(function () {
                checkbox = $(this).children(':checkbox');
                checkbox.is(":checked") ? checkbox.prop('checked', false) : checkbox.prop('checked', true);
            });
//Delete record
//            $('.delete').click(function () {
//                $('input[type="checkbox"][name*="check"]').prop('checked', false);
//                $(this).closest(".btn-group").find('input[type="checkbox"][name*="check"]').prop('checked', true);
//                $(this).closest("form#list").submit();
//            })
//Check All
//            $("#check-all").on('click', function () {
//                $('input[type="checkbox"][name*="check"]').prop('checked', $('input[type="checkbox"][name*="check"]:not(:checked)').length > 0);
//            });

//            $('form').submit(function () {
//                if (confirm("Подтвердить действие?") === false)
//                    return false;
//                else
//                    return true;
//            });

            $("#upload-form").click(function () {
                $("#upload-images").submit();
            });

            var flag = false;
            $(".delete-selected, .unconfirm-delete, .delete-this-id").click(function () {
                flag = !flag;
                if (flag)
                    move = "50%";
                else move = "-50%";

                $('.confirm-message').stop().animate({
                    top: move
                }, 300);
            });
            $(".confirm-delete").click(function () {
                $('#delete-form').submit();
            });
            $(".unconfirm-delete").click(function () {
                $('input[type=checkbox]:checked').prop('checked', false);
            });
            $(".delete-this-id").click(function () {
                $(this).closest().find('input:checkbox').prop('checked', true);
            });
            $("#check-all").on('click', function () {
                $('input[type="checkbox"][name*="check"]').prop('checked', $('input[type="checkbox"][name*="check"]:not(:checked)').length > 0);
            });
        });
    </script>
@stop