routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// TODO home page slider image by url! 


Auth::routes();



Route::group(['namespace' => 'Admin', 'prefix' => 'master', 'middleware' => ['auth', 'isMaster']], function () {
    Route::get('/', 'AdminHomeController@index')->name('master');
    Route::get('/products_management', 'AdminHomeController@productManagment')->name('product_managment');

    Route::resource('users', 'AdminUserController');
    Route::resource('settings', 'AdminSettingController', ['only' => ['edit', 'update']]);
    Route::resource('slider', 'AdminSliderController', ['except' => ['show']]);
    Route::resource('banner', 'AdminBannerController', ['except' => ['show', 'create', 'store']]);

    Route::post('rebuildtree', 'AdminBaseController@rebuildTree')->name('rebuildTree');


    Route::resource('page', 'AdminPageController', ['except' => ['show']]);
    Route::resource('portfolio', 'AdminPortfolioController');
    Route::resource('news', 'AdminNewsController', ['except' => ['show']]);
    Route::resource('currency', 'AdminCurrencyController', ['except' => ['show', 'destroy', 'create', 'edit']]);

    Route::group(['prefix' => 'products_management'], function () {
        Route::resource('categories', 'AdminCategoriesController', ['except' => ['show']]);
        Route::resource('brands', 'AdminBrandsController', ['except' => ['show']]);
        Route::resource('products', 'AdminProductsController');
        Route::get('products/loadAjax', 'AdminProductsController@loadAjax');
        Route::resource('labels', 'AdminLabelController', ['except' => ['show']]);
        Route::resource('options', 'AdminOptionsController', ['except' => ['show']]);
        Route::resource('colors', 'AdminColorController', ['except' => ['show', 'create']]);
        Route::resource('features', 'AdminFeatureController', ['except' => ['show']]);
        Route::resource('delivery', 'AdminDeliveryController', ['except' => ['show', 'create']]);
        Route::resource('payment', 'AdminPaymentController', ['except' => ['show', 'create']]);
        Route::resource('groups', 'AdminProductGroupsController');

    });

    // Orders
    Route::resource('order', 'AdminOrderController');
    Route::resource('comments', 'AdminCommentsController', ['except' => ['show', 'create', 'edit', 'store']]);
    Route::resource('questions', 'AdminProductQuestion');
    Route::resource('feedback', 'AdminFeedbackController');
    Route::resource('import', 'AdminImportController');

});


Route::group(['prefix' => LaravelLocalization::setLocale()], function () {
    /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
    Route::get('/', 'Site\HomeController@index');
    Route::get('/loadAjax/{data}', 'Site\HomeController@ajax');
    Route::get('/loadCart/{data}', 'Site\HomeController@loadCart');
    Route::post('/makeComment', 'Site\HomeController@makeComment');
    Route::post('question', 'Site\HomeController@makeQuestion');
    Route::post('feedback', 'Site\HomeController@makeFeedback');
    Route::get('/search', 'Site\HomeController@search');
    Route::get('catalog', 'Site\CatalogController@index');
    Route::get('catalog/{name}', 'Site\CatalogController@parse');
    Route::get('/personal', 'Site\PersonalController@index');
    Route::get('/personal/history', 'Site\PersonalController@history');
    Route::post('/personal/update', 'Site\PersonalController@update');
    Route::get('/cart', 'Site\OrderController@showCart');
    Route::get('/brand/{brand}', 'Site\PageController@showBrand');
	//Glide
    Route::get('img/{path}', function ($path, League\Glide\Server $server, Illuminate\Http\Request $request) {
        if ($request->w > 2000 || $request->h > 1000)
            return null;
        $server->outputImage('/images/' . $path, $request->all());
    })->where('path', '.+');
    Route::get('news/{new?}', 'Site\NewsController@index');
    Route::post('/addToCart', 'Site\OrderController@addToCart');
    Route::get('/makeconment', 'Site\HomeController@makeconment');
    Route::post('/dropFromCart', 'Site\OrderController@dropFromCart');
    Route::post('makeOrder', 'Site\OrderController@makeOrder');
    Route::get('/logout', function () {
        Auth::logout();
        return redirect('/');
    });
    Route::get('{page}', 'Site\PageController@index');
});

app/Models/ProductGroup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProductGroup extends Model
{
    protected $fillable = ['name'];

    public function products()
    {
        return $this->hasMany(Product::class, 'relgroup', 'id');
    }
}

resources/views/admin/product_groups/create.blade.php
@extends('admin.layout')

@section('main')

    <h1>{{ $title }}
        <a href="{{ route('brands.index') }}" class="btn btn-primary" title="Назад"
           data-toggle="tooltip"><span
                    class="fa fa-arrow-circle-left"></span></a>

        <button id="send-form" class="btn btn-success" title="Сохранить" data-toggle="tooltip"><i class="fa fa-floppy-o"
                                                                                                  aria-hidden="true"></i>
        </button>


        @if(Session::has('success'))
            <span class="btn alert-success" role="alert">{{ Session::get('success') }}</span>
        @elseif(Session::has('error'))
            <span class="btn alert-danger" role="alert">{{ Session::get('error') }}</span>
        @endif

        @if (count($errors) > 0)
            @foreach ($errors->all() as $error)
                <div class="btn alert-danger">
                    {{ $error }}
                </div>
            @endforeach
        @endif
    </h1><br>

    {!! Form::open(['route'=> ['brands.store'], 'class' => 'form-horizontal', 'role' => 'form', 'files' => true] ) !!}
    @include('admin.brands.form')
    {!! Form::close() !!}


    <script>
        $('#send-form').click(function () {
            $('form').submit();
        });

        meta_title_touched = false;
        url_touched = false;

        $('input[name="slug"]').change(function () {
            url_touched = true;
        });

        $('input[name="name[ru]"]').keyup(function () {
            if (!url_touched)
                $('input[name="slug"]').val(generate_url());

            if (!meta_title_touched)
                $('input[name="meta_title[ru]"]').val($('input[name="name[ru]"]').val());
        });

        $('input[name="meta_title"]').change(function () {
            meta_title_touched = true;
        });

        function generate_url() {
            url = $('input[name="name[ru]"]').val();
            url = url.replace(/[\s]+/gi, '-');
            url = translit(url);
            url = url.replace(/[^0-9a-z_\-]+/gi, '').toLowerCase();
            return url;
        }

        function translit(str) {
            var ru = ("А-а-Б-б-В-в-Ґ-ґ-Г-г-Д-д-Е-е-Ё-ё-Є-є-Ж-ж-З-з-И-и-І-і-Ї-ї-Й-й-К-к-Л-л-М-м-Н-н-О-о-П-п-Р-р-С-с-Т-т-У-у-Ф-ф-Х-х-Ц-ц-Ч-ч-Ш-ш-Щ-щ-Ъ-ъ-Ы-ы-Ь-ь-Э-э-Ю-ю-Я-я").split("-")
            var en = ("A-a-B-b-V-v-G-g-G-g-D-d-E-e-E-e-E-e-ZH-zh-Z-z-I-i-I-i-I-i-J-j-K-k-L-l-M-m-N-n-O-o-P-p-R-r-S-s-T-t-U-u-F-f-H-h-TS-ts-CH-ch-SH-sh-SCH-sch-'-'-Y-y-'-'-E-e-YU-yu-YA-ya").split("-")
            var res = '';
            for (var i = 0, l = str.length; i < l; i++) {
                var s = str.charAt(i), n = ru.indexOf(s);
                if (n >= 0) {
                    res += en[n];
                }
                else {
                    res += s;
                }
            }
            return res;
        }
    </script>
@stop

resources/views/admin/product_groups/edit.blade.php
@extends('admin.layout')
@section('main')
    <h1>{{ $title }}
        <a href="{{ route('groups.index') }}" class="btn btn-primary" title="Назад"
           data-toggle="tooltip"><span
                    class="fa fa-arrow-circle-left"></span></a>
      <button id="send-form" class="btn btn-success" title="Сохранить" data-toggle="tooltip"><i class="fa fa-floppy-o"
                                                                                              aria-hidden="true"></i>
    </button>
    </h1><br>

    {{ Form::model($item, ['route'=> ['groups.update', $item->id], 'class' => 'form-horizontal', 'role' => 'form'] ) }}
    {{ method_field('PATCH') }}
    @include('admin.product_groups.form')
    {{ Form::close() }}



    <script src="/admin/js/multiselect.min.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $('#search').multiselect({
                search: {
                    left: '<input type="text"  class="form-control" placeholder="Search..." />',
                    right: '<input type="text"  class="form-control" placeholder="Search..." />',
                },
                fireSearch: function(value) {
                    return value.length > 3;
                }
            });
        });
    </script>

    <script>
        $(function () {
            $('#send-form').click(function () {
                $('form').submit();
            });

            var skip = 1;
            var flag = true;

            $('#category_search').on('change', function(event){
                skip = 0;
                flag = false;
                $('#search').find('option').remove();
                
                    $.get('/master/products_management/groups/{{ $item->id }}/edit?skip='+skip+'&cat_id='+$(this).val(), function (response) {
                        console.log(response);
                        if (response != 0){
                            html = '';
                            for (key in response) {
                                html += '<option value="' + response[key].id + '">' + response[key].localization[0].name + '</option>';
                            }
                            $('#search').append(html);
                            ++skip;
                            flag = true;
                        }
                    });
            });

            $('#search').scroll(function () {
                if (this.scrollHeight - this.scrollTop < 900 && flag == true) {
                    flag = false;
                    $.get('/master/products_management/groups/{{ $item->id }}/edit?skip='+skip+'&cat_id='+$("#category_search").val(), function (response) {
                        console.log(response);
                        html = '';
                        for (key in response) {
                            html += '<option value="' + response[key].id + '">' + response[key].localization[0].name + '</option>';
                        }
                        $('#search').append(html);
                        ++skip;
                        flag = true;
                    });
                }

            });
        })
    </script>
@stop

resources/views/admin/product_groups/form.blade.php
<div class="form-group">
    {{ Form::label('body', 'Название группы', ['class'=>'col-sm-2 control-label'] ) }}
    <div class="col-sm-10">
        {{ Form::text('name', $item->name, ['class'=>'form-control'] ) }}
    </div>
</div>

<div class="row">
    <div class="col-xs-5">
        {{ Form::select("category_search", $categories, null, ['class' => 'form-control', 'id' => 'category_search']) }}
        <select name="from[]" id="search" class="form-control" size="8" multiple="multiple">
            @foreach($allProducts as $id => $name)
                <option value="{{$id}}">{{$name}}</option>
            @endforeach
        </select>
    </div>
    
    <div class="col-xs-2">
        <button type="button" id="search_rightAll" class="btn btn-block"><i class="glyphicon glyphicon-forward"></i></button>
        <button type="button" id="search_rightSelected" class="btn btn-block"><i class="glyphicon glyphicon-chevron-right"></i></button>
        <button type="button" id="search_leftSelected" class="btn btn-block"><i class="glyphicon glyphicon-chevron-left"></i></button>
        <button type="button" id="search_leftAll" class="btn btn-block"><i class="glyphicon glyphicon-backward"></i></button>
    </div>
    
    <div class="col-xs-5">
        <select name="to[]" id="search_to" class="form-control" size="8" multiple="multiple">
            @foreach($inGroup as $id => $name)
                <option value="{{$id}}">{{$name}}</option>
            @endforeach
        </select>
    </div>
</div>

@if($item->products)
    <table class="table">
        <tr>
            <th>Название</th>
            <th>Код</th>
            <th>Лейба</th>
            <th>Цвет</th>
            <th>Основная характеристика</th>
        </tr>
            @foreach($item->products as $product)
            <tr>
                <td>
                    <a href="{{ route('products.edit', $product->id) }}">
                        {{ $product->localization->where('locale', 'ru')->first()->name}}   
                    </a>
                </td>
                <td>
                    <span class="label label-primary">
                        {{$product->code}}
                    </span>
                </td>
                <td>
                    @if ($product->label)
                        <span class="label label-default" style="background-color: {{ $product->label->color }}">
                            {{ $product->label->localization->where('locale', 'ru')->first()->description }}
                        </span>
                    @endif
                </td>
                <td>
                    @if($product->color)
                        <span class="label label-primary" style="background-color: {{$product->color->value}}">
                            {{$product->color->name}}
                        </span>
                    @endif
                </td>
                <td>
                    @if ($product->mainFeature)
                        <span class="label label-primary">
                            {{ $product->mainFeature->localization->where('locale', 'ru')->first()->name }}:
                        </span>
                        &nbsp;
                        <span class="label label-success">
                            {{ $product->main_feature_text}}
                        </span>
                    @endif
                </td>
            </tr>
            @endforeach
    </table>
@endif

resources/views/admin/product_groups/index.blade.php
@extends('admin.layout')
@section('main')
    <h1>
        {{ $title }}
        <a href="{{ route('product_managment') }}" class="btn btn-primary" title="Назад" data-toggle="tooltip"><span
                    class="fa fa-arrow-circle-left"></span></a>

        <span class="btn btn-info" data-toggle="tooltip" title="Группы товаров нужны чтобы сгрупировать одинаковые товары по их основным характеристика/цветам">
            <i class="fa fa-info" aria-hidden="true"></i>
        </span>

        @if($items->total() > 0)
            <span class="btn btn-warning" title="Выбрать все" data-toggle="tooltip"
                  id="check-all"><i class="glyphicon glyphicon-ok"
                                    aria-hidden="true"></i></span>
            <button class="delete-selected btn btn-danger"
                    title="Удалить выбранные" data-toggle="tooltip">
                <span class="glyphicon glyphicon-trash"></span></button>

            <span class="label label-primary" style="font-size: 14px;">
			{{ $items->total() }}
                {{ Lang::choice('запись|записи|записей', $items->total(), [], 'ru') }}
        </span>
        @endif

        @if (count($errors) > 0)
            @foreach ($errors->all() as $error)
                <div class="btn alert-danger">
                    {{ $error }}
                </div>
            @endforeach
        @endif
    </h1><br>

    {{ Form::open(['route' => ['groups.store']]) }}
    {{ Form::label('name', 'Название группы', ['class'=>'col-sm-2 control-label text-right'] ) }}
    <div class="col-sm-2">
        {{ Form::text("name", '', ['class'=>'form-control', 'data-toggle' => 'tooltip', 'required', 'autocomplete' => 'off'] ) }}
    </div>
    <button class="btn btn-success fa fa-plus" data-toggle="tooltip" title="Добавить"></button>
    {{ Form::close() }}

    @if ($items->total() > 0)


        {!! Form::open(['route' => ['groups.destroy', 'destroy']]) !!}
        {{ method_field('DELETE') }}
        {{ Form::hidden('parent', true) }}
        <table class="table">
            <tr>
                <th style="width: 70%;">Название группы</th>
                <th style="text-align: right;">Управление</th>
            </tr>
            @foreach ($items as $item)
                <tr>
                    <td style="vertical-align: middle">
                        {{ Form::checkbox('check[]', $item->id, false, ['id' => 'check'.$item->id, 'class' => 'custom-check']) }}
                        {{ Form::label('check'.$item->id, '1', ['class' => 'custom-label-for-check']) }}
                        {{ csrf_field() }}
                        <a href="{{ route('groups.edit', $item->id) }}">
                            {{ $item->name }}
                        </a>
                    </td>
                    <td style="text-align: right;">
                        <a title="Редактировать" href="{{ route('groups.edit', ['id' => $item->id]) }}"
                           data-toggle="tooltip"
                           class="btn btn-default"><span class="fa fa-pencil"></span></a>
                        <span class="delete-this-id btn btn-default" title="Удалить"
                              data-toggle="tooltip"><span
                                    class="glyphicon glyphicon-remove"></span>
                            </span>
                    </td>
                </tr>
            @endforeach
        </table>
        {{ Form::close() }}

    @endif

    {{ $items->links() }}

    <script>
        $(function () {
            var flag = false;
            $(".delete-selected, .unconfirm-delete, .delete-this-id").click(function () {
                flag = !flag;
                if (flag)
                    move = "50%";
                else move = "-50%";

                $('.confirm-message').stop().animate({
                    top: move
                }, 300);
            });
            $(".confirm-delete").click(function () {
                $('form').submit();
            });
            $(".unconfirm-delete").click(function () {
                $('input[type=checkbox]:checked').prop('checked', false);
            });
            $(".delete-this-id").click(function () {
                $(this).closest('tr').find('input:checkbox').prop('checked', true);
            });
            $("#check-all").on('click', function () {
                $('input[type="checkbox"][name*="check"]').prop('checked', $('input[type="checkbox"][name*="check"]:not(:checked)').length > 0);
            });
        })
    </script>
@endsection