routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// TODO home page slider image by url! 


Auth::routes();



Route::group(['namespace' => 'Admin', 'prefix' => 'master', 'middleware' => ['auth', 'isMaster']], function () {
    Route::get('/', 'AdminHomeController@index')->name('master');
    Route::get('/products_management', 'AdminHomeController@productManagment')->name('product_managment');

    Route::resource('users', 'AdminUserController');
    Route::resource('settings', 'AdminSettingController', ['only' => ['edit', 'update']]);
    Route::resource('slider', 'AdminSliderController', ['except' => ['show']]);
    Route::resource('banner', 'AdminBannerController', ['except' => ['show', 'create', 'store']]);

    Route::post('rebuildtree', 'AdminBaseController@rebuildTree')->name('rebuildTree');


    Route::resource('page', 'AdminPageController', ['except' => ['show']]);
    Route::resource('portfolio', 'AdminPortfolioController');
    Route::resource('news', 'AdminNewsController', ['except' => ['show']]);
    Route::resource('currency', 'AdminCurrencyController', ['except' => ['show', 'destroy', 'create', 'edit']]);

    Route::group(['prefix' => 'products_management'], function () {
        Route::resource('categories', 'AdminCategoriesController', ['except' => ['show']]);
        Route::resource('brands', 'AdminBrandsController', ['except' => ['show']]);
        Route::resource('products', 'AdminProductsController');
        Route::get('products/loadAjax', 'AdminProductsController@loadAjax');
        Route::resource('labels', 'AdminLabelController', ['except' => ['show']]);
        Route::resource('options', 'AdminOptionsController', ['except' => ['show']]);
        Route::resource('colors', 'AdminColorController', ['except' => ['show', 'create']]);
        Route::resource('features', 'AdminFeatureController', ['except' => ['show']]);
        Route::resource('delivery', 'AdminDeliveryController', ['except' => ['show', 'create']]);
        Route::resource('payment', 'AdminPaymentController', ['except' => ['show', 'create']]);
        Route::resource('groups', 'AdminProductGroupsController');

    });

    // Orders
    Route::resource('order', 'AdminOrderController');
    Route::resource('comments', 'AdminCommentsController', ['except' => ['show', 'create', 'edit', 'store']]);
    Route::resource('questions', 'AdminProductQuestion');
    Route::resource('feedback', 'AdminFeedbackController');
    Route::resource('import', 'AdminImportController');

});


Route::group(['prefix' => LaravelLocalization::setLocale()], function () {
    /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
    Route::get('/', 'Site\HomeController@index');
    Route::get('/loadAjax/{data}', 'Site\HomeController@ajax');
    Route::get('/loadCart/{data}', 'Site\HomeController@loadCart');
    Route::post('/makeComment', 'Site\HomeController@makeComment');
    Route::post('question', 'Site\HomeController@makeQuestion');
    Route::post('feedback', 'Site\HomeController@makeFeedback');
    Route::get('/search', 'Site\HomeController@search');
    Route::get('catalog', 'Site\CatalogController@index');
    Route::get('catalog/{name}', 'Site\CatalogController@parse');
    Route::get('/personal', 'Site\PersonalController@index');
    Route::get('/personal/history', 'Site\PersonalController@history');
    Route::post('/personal/update', 'Site\PersonalController@update');
    Route::get('/cart', 'Site\OrderController@showCart');
    Route::get('/brand/{brand}', 'Site\PageController@showBrand');
	//Glide
    Route::get('img/{path}', function ($path, League\Glide\Server $server, Illuminate\Http\Request $request) {
        if ($request->w > 2000 || $request->h > 1000)
            return null;
        $server->outputImage('/images/' . $path, $request->all());
    })->where('path', '.+');
    Route::get('news/{new?}', 'Site\NewsController@index');
    Route::post('/addToCart', 'Site\OrderController@addToCart');
    Route::get('/makeconment', 'Site\HomeController@makeconment');
    Route::post('/dropFromCart', 'Site\OrderController@dropFromCart');
    Route::post('makeOrder', 'Site\OrderController@makeOrder');
    Route::get('/logout', function () {
        Auth::logout();
        return redirect('/');
    });
    Route::get('{page}', 'Site\PageController@index');
});

resources/views/admin/home.blade.php
@extends('admin.layout')

@section('main')

    <div class="row pages">

        <div class="col-sm-12">
            <h1>Управление контентом</h1>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('page.index',['type' => 'main']) }}">
                <i class="fa fa-rocket fa-4x"></i>
                <p>Страницы основного меню</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('page.index',['type' => 'top']) }}">
                <i class="fa fa-space-shuttle fa-4x"></i>
                <p>Страницы топ меню</p>
            </a>
        </div>


        {{--<div class="col-md-2 col-sm-3 col-xs-4">--}}
            {{--<a href="{{ route('portfolio.index') }}">--}}
                {{--<i class="fa fa-camera fa-4x"></i>--}}
                {{--<span>Портфолио</span>--}}
            {{--</a>--}}
        {{--</div>--}}

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('slider.index') }}">
                <i class="fa fa-sliders fa-4x"></i>
                <p>Слайдер</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('banner.index') }}">
                <i class="fa fa-sliders fa-4x"></i>
                <p>Баннер</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('currency.index') }}">
                <i class="fa fa-usd fa-4x"></i>
                <p>Валюта</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('news.index') }}">
                <i class="fa fa-newspaper-o fa-4x"></i>
                <p>Новости</p>
            </a>
        </div>

    </div>

@stop

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }} @if( isset( $site_offline ) && $site_offline == 1 )OFFLINE @endif</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link href="/dashboard/css/bootstrap-switch.min.css" rel="stylesheet">
    <link href="/dashboard/css/magnific.css" rel="stylesheet">
    <link href="/admin/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/flags.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/css/custom.css') }}">
    <link href="/dashboard/bower_components/angular/angular-ui-tree.min.css" rel="stylesheet">
    {{--<script src="/dashboard/js/jquery.js"></script>--}}
    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    @section('styles')
    @show

    <script src="/dashboard/js/magnific.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="/dashboard/js/bootstrap.filestyle.js"></script>
    <script src="/dashboard/js/bootstrap-switch.min.js"></script>
    <script src="/dashboard/js/bootstrap-growl.min.js"></script>
    @section('scripts')
	@show
	<!--[if lt IE 9]>
    <script src="/frontend/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="icon @if( in_array( Request::segment(2), ['settings'] )) active @endif">
                <a class="navbar-brand" href="{{ route('settings.edit', 1) }}">
                    <i class="fa fa-cog @if( in_array( Request::segment(2), ['settings'] )) fa-spin @endif fa-2x"></i>
                </a>
            </li>
            <li @if( in_array( Request::segment(2), ['','page', 'articles', 'news', 'slider', 'portfolio'] ) ) class="active"@endif>
                <a href="/master">Управление контентом<span class="sr-only">(current)</span></a>
                <ul>
                    @foreach($navigation['content'] as $key => $value)
                        <li><a href="{{ url($value) }}"><p>{{$key}}</p></a></li>
                    @endforeach
                </ul>
            </li>
            <li @if( in_array( Request::segment(2), ['products_management','categories', 'payment', 'products', 'delivery', 'features', 'option_variants'] ) ) class="active"@endif>
                <a href="/master/products_management">Управление товаром</a>
                <ul>
                    @foreach($navigation['product'] as $key => $value)
                        <li><a href="{{ url($value) }}"><p>{{$key}}</p></a></li>
                    @endforeach
                </ul>
            </li>
            <li @if( Request::segment(2) == 'order' ) class="active" @endif title="Заказы" data-toggle="tooltip"
                data-placement="bottom">
                <a href="{{ route('order.index') }}">
                    <i style="font-size: 18px;" class="fa fa-cart-plus" aria-hidden="true"></i>
                    @if ($new_orders > 0)
                        <label class="label label-primary">
                            {{ $new_orders }}
                        </label>
                    @endif
                </a>
            </li>
            <li @if( Request::segment(2) == 'questions' ) class="active" @endif title="Вопросы покупателей"
                data-toggle="tooltip" data-placement="bottom">
                <a href="{{ route('questions.index') }}">
                    <i style="font-size: 18px;" class="fa fa-weixin" aria-hidden="true"></i>
                    @if ($new_questions > 0)
                        <label class="label label-primary">
                            {{ $new_questions }}
                        </label>
                    @endif
                </a>
            </li>
            <li @if( Request::segment(2) == 'feedback' ) class="active"
                @endif title="Обратная связь (Заказы обратных звонков)"
                data-toggle="tooltip" data-placement="bottom">
                <a href="{{ route('feedback.index') }}">
                    <i style="font-size: 18px;" class="fa fa-volume-control-phone" aria-hidden="true"></i>
                    @if ($feedback > 0)
                        <label class="label label-primary">
                            {{ $feedback }}
                        </label>
                    @endif
                </a>
            </li>
            <li @if( Request::segment(2) == 'comments' ) class="active"
                @endif title="Комментарии пользователей" data-toggle="tooltip" data-placement="bottom">
                <a href="{{ route('comments.index') }}">
                    <i style="font-size: 18px;" class="fa fa-commenting" aria-hidden="true"></i>
                    @if ($comments)
                        <label class="label label-primary">
                            {{$comments}}
                        </label>
                    @endif
                </a>
            </li>
            <li @if( Request::segment(2) == 'import' ) class="active" @endif title="Импорт (Документ XML)"
                data-toggle="tooltip"
                data-placement="bottom">
                <a href="{{ route('import.index') }}">
                    <i style="font-size: 18px;" class="fa fa-cloud-upload" aria-hidden="true"></i>
                </a>
            </li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="icon gotosite"><a target="_blank" href="/">
                    <div class="goto">Перейти на сайт</div>
                    <i class="fa fa-arrow-circle-o-right fa-3x"></i></a></li>
            <li><a href="/logout" class="logout"><i class="fa fa-sign-in"></i> Выход</a></li>
            <li class="icon" title="Пользователи" data-toggle="tooltip">
                <a class="navbar-brand" href="{{ route('users.index') }}">
                    <i class="fa fa-user-circle-o fa-2x"></i>
                </a>
            </li>
        </ul>
    </div>
    <!-- /.container-fluid -->
</nav>
<div class="confirm-message">
    <p>Подтвердите удаление записей из БД?</p> &nbsp;
    <span class="confirm-delete btn btn-success">Да</span>
    <span class="unconfirm-delete btn btn-danger">Нет</span>
</div>
@if(Session::has('success'))
    <div class="message message-success">
        {{-- <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        {{-- <span class="sr-only">Success:</span> --}}
        <i class="fa fa-check"></i>
        {{ Session::get('success') }}
    </div>
@elseif(Session::has('error'))
    <div class="message message-error">
        <span class="fa fa-times" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        {{ Session::get('error') }}
    </div>
@elseif(Session::has('warning'))
    <div class="message message-warning">
        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
        <span class="sr-only">Warning:</span>
        {{ Session::pull('warning') }}
    </div>
@elseif(Session::has('info'))
    <div class="message message-warning">
        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
        <span class="sr-only">Info:</span>
        {{ Session::pull('info') }}
    </div>
@endif

<div class="container-fluid">
    <div id="show_page">
        @yield('main')
    </div>
</div>

<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
    $(function () {
        $('.leopard').animate({
            'left': "100vw"
        }, 6000, function () {
            $(this).remove();
        });


        $('[data-toggle="tooltip"]').tooltip();
        $('.editor').ckeditor();

        if ($('.message').html()) {
            $('.message').animate({
                'opacity': 1,
                'top': "20vh"
            }, 1000, function () {
                setTimeout(function () {
                    $('.message').animate({
                        'opacity': 0,
                        'top': "-10%"
                    }, 700, function () {
                        $('.message').remove();
                    });
                }, 2500);
            });
        }

        function confirmDelete() {

            return true;
        }

        $(document).ready(function () {
            $('.nav-block').addClass('animate-this');
        });

        function printS(text) {
            return console.log('%c' + text, 'background: black; font-size: 18px; color: greenyellow; font-weight: bolder');
        }
    });
</script>
@yield('scripts')
</body>
</html>

resources/views/admin/product_managment.blade.php
@extends('admin.layout')

@section('main')

    <div class="row pages">

        <div class="col-sm-12">
            <h1>Управление Товаром</h1>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('categories.index') }}">
                <i class="fa fa-thumb-tack fa-4x"></i>
                <p>Категории</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('features.index') }}">
                <i class="fa fa-leaf fa-4x"></i>
                <p>Параметры фильтрации</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('options.index') }}">
                <i class="fa fa-bolt fa-4x"></i>
                <p>Характеристики продуктов</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('brands.index') }}">
                <i class="fa fa-gg-circle fa-4x"></i>
                <p>Бренды</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('labels.index') }}">
                <i class="fa fa-bookmark-o fa-4x"></i>
                <p>Лейбы</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('colors.index') }}">
                <i class="fa fa-lightbulb-o fa-4x"></i>
                <p>Цвета продуктов</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('products.index') }}">
                <i class="fa fa-cubes fa-4x"></i>
                <p>Продукты</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('groups.index') }}">
                <i class="fa fa-cubes fa-4x"></i>
                <p>Группы продуктов</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('delivery.index') }}">
                <i class="fa fa-truck fa-4x"></i>
                <p>Доставка</p>
            </a>
        </div>

        <div class="col-md-2 col-sm-3 col-xs-4 nav-block">
            <a href="{{ route('payment.index') }}">
                <i class="fa fa-money fa-4x"></i>
                <p>Оплата</p>
            </a>
        </div>

    </div>

@stop