routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// TODO home page slider image by url! 


Auth::routes();



Route::group(['namespace' => 'Admin', 'prefix' => 'master', 'middleware' => ['auth', 'isMaster']], function () {
    Route::get('/', 'AdminHomeController@index')->name('master');
    Route::get('/products_management', 'AdminHomeController@productManagment')->name('product_managment');

    Route::resource('users', 'AdminUserController');
    Route::resource('settings', 'AdminSettingController', ['only' => ['edit', 'update']]);
    Route::resource('slider', 'AdminSliderController', ['except' => ['show']]);
    Route::resource('banner', 'AdminBannerController', ['except' => ['show', 'create', 'store']]);

    Route::post('rebuildtree', 'AdminBaseController@rebuildTree')->name('rebuildTree');


    Route::resource('page', 'AdminPageController', ['except' => ['show']]);
    Route::resource('portfolio', 'AdminPortfolioController');
    Route::resource('news', 'AdminNewsController', ['except' => ['show']]);
    Route::resource('currency', 'AdminCurrencyController', ['except' => ['show', 'destroy', 'create', 'edit']]);

    Route::group(['prefix' => 'products_management'], function () {
        Route::resource('categories', 'AdminCategoriesController', ['except' => ['show']]);
        Route::resource('brands', 'AdminBrandsController', ['except' => ['show']]);
        Route::resource('products', 'AdminProductsController');
        Route::get('products/loadAjax', 'AdminProductsController@loadAjax');
        Route::resource('labels', 'AdminLabelController', ['except' => ['show']]);
        Route::resource('options', 'AdminOptionsController', ['except' => ['show']]);
        Route::resource('colors', 'AdminColorController', ['except' => ['show', 'create']]);
        Route::resource('features', 'AdminFeatureController', ['except' => ['show']]);
        Route::resource('delivery', 'AdminDeliveryController', ['except' => ['show', 'create']]);
        Route::resource('payment', 'AdminPaymentController', ['except' => ['show', 'create']]);
        Route::resource('groups', 'AdminProductGroupsController');

    });

    // Orders
    Route::resource('order', 'AdminOrderController');
    Route::resource('comments', 'AdminCommentsController', ['except' => ['show', 'create', 'edit', 'store']]);
    Route::resource('questions', 'AdminProductQuestion');
    Route::resource('feedback', 'AdminFeedbackController');
    Route::resource('import', 'AdminImportController');

});


Route::group(['prefix' => LaravelLocalization::setLocale()], function () {
    /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
    Route::get('/', 'Site\HomeController@index');
    Route::get('/loadAjax/{data}', 'Site\HomeController@ajax');
    Route::get('/loadCart/{data}', 'Site\HomeController@loadCart');
    Route::post('/makeComment', 'Site\HomeController@makeComment');
    Route::post('question', 'Site\HomeController@makeQuestion');
    Route::post('feedback', 'Site\HomeController@makeFeedback');
    Route::get('/search', 'Site\HomeController@search');
    Route::get('catalog', 'Site\CatalogController@index');
    Route::get('catalog/{name}', 'Site\CatalogController@parse');
    Route::get('/personal', 'Site\PersonalController@index');
    Route::get('/personal/history', 'Site\PersonalController@history');
    Route::post('/personal/update', 'Site\PersonalController@update');
    Route::get('/cart', 'Site\OrderController@showCart');
    Route::get('/brand/{brand}', 'Site\PageController@showBrand');
	//Glide
    Route::get('img/{path}', function ($path, League\Glide\Server $server, Illuminate\Http\Request $request) {
        if ($request->w > 2000 || $request->h > 1000)
            return null;
        $server->outputImage('/images/' . $path, $request->all());
    })->where('path', '.+');
    Route::get('news/{new?}', 'Site\NewsController@index');
    Route::post('/addToCart', 'Site\OrderController@addToCart');
    Route::get('/makeconment', 'Site\HomeController@makeconment');
    Route::post('/dropFromCart', 'Site\OrderController@dropFromCart');
    Route::post('makeOrder', 'Site\OrderController@makeOrder');
    Route::get('/logout', function () {
        Auth::logout();
        return redirect('/');
    });
    Route::get('{page}', 'Site\PageController@index');
});

app/Models/Color.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    protected $fillable = ['name', 'value'];
}

resources/views/admin/colors/create.blade.php
@extends('admin.layout')

@section('main')

    <h1>{{ $title }}
        <a href="{{ route('news.index') }}" class="btn btn-primary" title="Назад"
           data-toggle="tooltip"><span
                    class="fa fa-arrow-circle-left"></span></a>

        <button id="send-form" class="btn btn-success" title="Сохранить" data-toggle="tooltip"><i class="fa fa-floppy-o"
                                                                                                  aria-hidden="true"></i>
        </button>


        @if(Session::has('success'))
            <span class="btn alert-success" role="alert">{{ Session::get('success') }}</span>
        @elseif(Session::has('error'))
            <span class="btn alert-danger" role="alert">{{ Session::get('error') }}</span>
        @endif

        @if (count($errors) > 0)
            @foreach ($errors->all() as $error)
                <div class="btn alert-danger">
                    {{ $error }}
                </div>
            @endforeach
        @endif
    </h1><br>

    {!! Form::open(['route'=> ['news.store'], 'class' => 'form-horizontal', 'role' => 'form', 'files' => true] ) !!}
    @include('admin.news.form')
    {!! Form::close() !!}


    <script>
        $('#send-form').click(function () {
            $('form').submit();
        });

        meta_title_touched = false;
        url_touched = false;

        $('input[name="slug"]').change(function () {
            url_touched = true;
        });

        $('input[name="name[ru]"]').keyup(function () {
            if (!url_touched)
                $('input[name="slug"]').val(generate_url());

            if (!meta_title_touched)
                $('input[name="meta_title[ru]"]').val($('input[name="name[ru]"]').val());
        });

        $('input[name="meta_title"]').change(function () {
            meta_title_touched = true;
        });

        function generate_url() {
            url = $('input[name="name[ru]"]').val();
            url = url.replace(/[\s]+/gi, '-');
            url = translit(url);
            url = url.replace(/[^0-9a-z_\-]+/gi, '').toLowerCase();
            return url;
        }

        function translit(str) {
            var ru = ("А-а-Б-б-В-в-Ґ-ґ-Г-г-Д-д-Е-е-Ё-ё-Є-є-Ж-ж-З-з-И-и-І-і-Ї-ї-Й-й-К-к-Л-л-М-м-Н-н-О-о-П-п-Р-р-С-с-Т-т-У-у-Ф-ф-Х-х-Ц-ц-Ч-ч-Ш-ш-Щ-щ-Ъ-ъ-Ы-ы-Ь-ь-Э-э-Ю-ю-Я-я").split("-")
            var en = ("A-a-B-b-V-v-G-g-G-g-D-d-E-e-E-e-E-e-ZH-zh-Z-z-I-i-I-i-I-i-J-j-K-k-L-l-M-m-N-n-O-o-P-p-R-r-S-s-T-t-U-u-F-f-H-h-TS-ts-CH-ch-SH-sh-SCH-sch-'-'-Y-y-'-'-E-e-YU-yu-YA-ya").split("-")
            var res = '';
            for (var i = 0, l = str.length; i < l; i++) {
                var s = str.charAt(i), n = ru.indexOf(s);
                if (n >= 0) {
                    res += en[n];
                }
                else {
                    res += s;
                }
            }
            return res;
        }
    </script>
@stop

resources/views/admin/colors/edit.blade.php
@extends('admin.layout')

@section('main')

    <h1>{{ $title }}
        <a href="{{ route('colors.index') }}" class="btn btn-primary" title="Назад"
           data-toggle="tooltip"><span
                    class="fa fa-arrow-circle-left"></span></a>

        <button id="send-form" class="btn btn-success" title="Сохранить" data-toggle="tooltip"><i class="fa fa-floppy-o"
                                                                                                  aria-hidden="true"></i>
        </button>

        @if (count($errors) > 0)
            @foreach ($errors->all() as $error)
                <div class="btn alert-danger">
                    {{ $error }}
                </div>
            @endforeach
        @endif
    </h1><br>

    {{ Form::model($item, ['route'=> ['colors.update', $item->id], 'class' => 'form-horizontal', 'role' => 'form'] ) }}
    <div class="form-group">
        {{ method_field('PATCH') }}
        {{ Form::label('name', 'Название', ['class'=>'col-sm-1 control-label'] ) }}
        <div class="col-sm-2">
            {{ Form::text("name", $item->name, ['class'=>'form-control'] ) }}
        </div>
        {{ Form::label('value', 'Цвет', ['class'=>'col-sm-1 control-label'] ) }}
        <div class="col-sm-2">
            {{ Form::color("value", $item->value, ['class'=>'form-control'] ) }}
        </div>
    </div>
    {{ Form::close() }}

    <script>
        $('#send-form').click(function () {
            $('form').submit();
        });
    </script>
@stop

resources/views/admin/colors/form.blade.php
<?php $count = 0; ?>
<ul class="nav nav-tabs" id="myTab">
    @foreach(LaravelLocalization::getSupportedLocales() as $key => $value)
        <li @if($count == 0) class="active" @endif data-toggle="tooltip" title="{{ $value['native']}}">
            <a href="#tab_{{ $key }}" data-toggle="tab">&nbsp;&nbsp;&nbsp;&nbsp;<span
                        class="flag flag-{{ $key }}"></span>
            </a>
        </li>
        <?php $count++ ?>
    @endforeach
    <li>
        <div class="col-sm-12">
            {{ Form::text('slug', old('slug') ? old('slug') : $page->slug, [
            'class'=>'form-control',
            'data-toggle' => 'tooltip',
            'title' => 'Адрес страницы'
            ]) }}
        </div>
    </li>
</ul>
<?php $count = 0; ?>

<div class="form-group">
    {!! Form::label('image', 'Изображение новости', array('class'=>'col-sm-2 control-label') ) !!}
    <div class="col-sm-9">
        {!! Form::file('image[]',array('class' => 'filestyle', 'data-value'=> '',
        'data-buttonText' => 'Выберите файлы', 'data-buttonName' => 'btn-primary',
        'data-icon' => 'true' , 'multiple' => 'true') ) !!}
        <span>Если изображение не соответствует размеру 255x96, оно будет автоматически обрезано до данной величины</span>
    </div>
</div>

<div class="tab-content">
    @foreach(LaravelLocalization::getSupportedLocales() as $key => $value)
        @forelse($page->localization as $data)
            @if ($data['locale'] == $key)
                <div class="tab-pane @if ($count == 0) active @endif" id="tab_{{ $key }}">
                    <div class="tab-content">

                        <div class="form-group">
                            {{ Form::label('name' . $key, 'Заголовок', ['class'=>'col-sm-2 control-label'] ) }}
                            <div class="col-sm-10">
                                {{ Form::text("name[$key]", $data->name, ['class'=>'form-control'] ) }}
                            </div>
                        </div>

                        <div class="form-group">
                            {{ Form::label('body' . $key, 'Полный текст страницы', ['class'=>'col-sm-2 control-label'] ) }}
                            <div class="col-sm-10">
                                {{ Form::textarea("body[$key]", $data->body, ['class'=>'form-control editor'] ) }}
                            </div>
                        </div>

                        <div class="form-group">
                            {{ Form::label('meta_title' . $key, 'Meta Title', ['class'=>'col-sm-2 control-label'] ) }}
                            <div class="col-sm-10">
                                {{ Form::text("meta_title[$key]", $data->meta_title, ['class'=>'form-control', 'id' => 'inputMetaTitle'] ) }}
                            </div>
                        </div>

                        <div class="form-group">
                            {{ Form::label('meta_keywords' . $key, 'Meta Keys', ['class'=>'col-sm-2 control-label'] ) }}
                            <div class="col-sm-10">
                                {{ Form::text("meta_keywords[$key]", $data->meta_keywords, ['class'=>'form-control', 'id' => 'inputMetaTitle'] ) }}
                            </div>
                        </div>

                        <div class="form-group">
                            {{ Form::label('meta_description' . $key, 'Meta Description', ['class'=>'col-sm-2 control-label'] ) }}
                            <div class="col-sm-10">
                                {{ Form::text("meta_description[$key]", $data->meta_description, ['class'=>'form-control'] ) }}
                            </div>
                        </div>

                    </div>
                </div>
            @endif
        @empty
            <div class="tab-pane @if ($count == 0) active @endif" id="tab_{{ $key }}">
                <div class="tab-content">

                    <div class="form-group">
                        {{ Form::label('name' . $key, 'Заголовок', ['class'=>'col-sm-2 control-label'] ) }}
                        <div class="col-sm-10">
                            {{ Form::text("name[$key]", '', ['class'=>'form-control'] ) }}
                        </div>
                    </div>

                    <div class="form-group">
                        {{ Form::label('body' . $key, 'Полный текст страницы', ['class'=>'col-sm-2 control-label'] ) }}
                        <div class="col-sm-10">
                            {{ Form::textarea("body[$key]", '', ['class'=>'form-control editor'] ) }}
                        </div>
                    </div>

                    <div class="form-group">
                        {{ Form::label('meta_title' . $key, 'Meta Title', ['class'=>'col-sm-2 control-label'] ) }}
                        <div class="col-sm-10">
                            {{ Form::text("meta_title[$key]", '', ['class'=>'form-control', 'id' => 'inputMetaTitle'] ) }}
                        </div>
                    </div>

                    <div class="form-group">
                        {{ Form::label('meta_keywords' . $key, 'Meta Keys', ['class'=>'col-sm-2 control-label'] ) }}
                        <div class="col-sm-10">
                            {{ Form::text("meta_keywords[$key]", '', ['class'=>'form-control', 'id' => 'inputMetaTitle'] ) }}
                        </div>
                    </div>

                    <div class="form-group">
                        {{ Form::label('meta_description' . $key, 'Meta Description', ['class'=>'col-sm-2 control-label'] ) }}
                        <div class="col-sm-10">
                            {{ Form::text("meta_description[$key]", '', ['class'=>'form-control'] ) }}
                        </div>
                    </div>

                </div>
            </div>
        @endforelse
        <?php $count++ ?>
    @endforeach
</div>

resources/views/admin/colors/index.blade.php
@extends('admin.layout')
@section('main')
    <h1>
        <span class="fa fa-newspaper-o"></span>
        {{ $title }}
        <a href="{{ route('product_managment') }}" class="btn btn-primary" title="Назад" data-toggle="tooltip"><span
                    class="fa fa-arrow-circle-left"></span></a>

        @if($items->total() > 0)
            <span class="btn btn-warning" title="Выбрать все" data-toggle="tooltip"
                  id="check-all"><i class="glyphicon glyphicon-ok"
                                    aria-hidden="true"></i></span>
            <button class="delete-selected btn btn-danger"
                    title="Удалить выбранные" data-toggle="tooltip">
                <span class="glyphicon glyphicon-trash"></span></button>

            <span class="label label-primary" style="font-size: 14px;">
			{{ $items->total() }}
                {{ Lang::choice('цвет|цвета|цветов', $items->total(), [], 'ru') }}
        </span>
        @endif

        @if (count($errors) > 0)
            @foreach ($errors->all() as $error)
                <div class="btn alert-danger">
                    {{ $error }}
                </div>
            @endforeach
        @endif
    </h1><br>

    {!! Form::open(['route'=> ['colors.store'], 'class' => 'form-horizontal', 'role' => 'form', 'files' => true] ) !!}
    <div class="form-group">
        {{ Form::label('name', 'Название', ['class'=>'col-sm-1 control-label'] ) }}
        <div class="col-sm-2">
            {{ Form::text("name", "", ['class'=>'form-control'] ) }}
        </div>
        {{ Form::label('value', 'Цвет', ['class'=>'col-sm-1 control-label'] ) }}
        <div class="col-sm-2">
            {{ Form::color("value", "", ['class'=>'form-control'] ) }}
        </div>
        <button class="fa fa-floppy-o btn btn-success" data-toggle="tooltip" title="Создать"></button>
    </div>
    {!! Form::close() !!}

    @if ($items->total() > 0)
        <hr>
        {!! Form::open(['route' => ['colors.destroy', 'destroy']]) !!}
        {{ method_field('DELETE') }}
        <table class="table">
            <tr>
                <th style="width: 20%;">Название</th>
                <th>Цвет</th>
                <th style="text-align: right;">Управление</th>
            </tr>
            @foreach ($items as $item)
                <tr>
                    <td style="vertical-align: middle">
                        {{ Form::checkbox('check[]', $item->id, false, ['id' => 'check'.$item->id, 'class' => 'custom-check']) }}
                        {{ Form::label('check'.$item->id, '1', ['class' => 'custom-label-for-check']) }}
                        {{--<input name="check[]" value="{{ $item->id }}"type="checkbox">--}}
                        <a class="black_link" title="Редактировать новость" data-toggle="tooltip"
                           href="{{ route('colors.edit', $item->id) }}">
                            {{ $item->name }}</a>
                    </td>
                    <td>
                        <div style="background: rgba(0,0,0,.1); display: inline-block; padding: 2px 5px">
                            <span class="fa fa-circle"
                                  style="color: {{ $item->value }}; font-size: 25px"></span>
                        </div>
                    </td>
                    <td style="text-align: right;">
                        <a title="Редактировать" href="{{ route('colors.edit', ['id' => $item->id]) }}"
                           data-toggle="tooltip"
                           class="btn btn-primary"><span class="fa fa-pencil"></span></a>
                        <span class="delete-this-id btn btn-default" title="Удалить"
                              data-toggle="tooltip"><span
                                    class="fa fa-times"></span>
                        </span>
                    </td>
                </tr>
            @endforeach
        </table>
        {{ Form::close() }}

    @endif
    {{--    {{ $items->links() }}--}}

    <script>
        $(function () {

            var flag = false;
            $(".delete-selected, .unconfirm-delete, .delete-this-id").click(function () {
                flag = !flag;
                if (flag)
                    move = "50%";
                else move = "-50%";

                $('.confirm-message').stop().animate({
                    top: move
                }, 300);
            });
            $(".confirm-delete").click(function () {
                $('form').submit();
            });
            $(".unconfirm-delete").click(function () {
                $('input[type=checkbox]:checked').prop('checked', false);
            });
            $(".delete-this-id").click(function () {
                $(this).closest('tr').find('input:checkbox').prop('checked', true);
            });
            $("#check-all").on('click', function () {
                $('input[type="checkbox"][name*="check"]').prop('checked', $('input[type="checkbox"][name*="check"]:not(:checked)').length > 0);
            });
        })
    </script>
@endsection